version: '3'

services:
  web:
    image: node:18-alpine
    ports:
      - "8998:8998"
    environment:
      - PORT=8998
    volumes:
      - config-data:/data
    working_dir: /app
    command: >
      sh -c "apk add --no-cache git &&
             mkdir -p /data &&
             if [ -d /app/.git ]; then
               echo 'Repository exists, updating...' &&
               git pull || echo 'Failed to pull, continuing with existing code'
             else
               echo 'First run, preparing directory...' &&
               cd / &&
               rm -rf /app &&
               mkdir -p /app &&
               echo 'Cloning repository...' &&
               git clone https://github.com/mattywhitenz/vapiweb.git /app &&
               cd /app
             fi &&
             echo 'Installing dependencies...' &&
             npm install &&
             echo 'Setting up config file...' &&
             ln -sf /data/config.json /app/config.json || true &&
             echo 'Starting server...' &&
             node server.js"
    restart: unless-stopped

volumes:
  config-data:
    driver: local 